### PR TITLE
Remove the last use of ament_target_dependencies.

### PR DESCRIPTION
**Pull request by clalancette**

### CODE REVIEW

**Comment by Creador270** [comment]
Hi, I'm using Debian 12 bookworm and doing a colcon build, I get the error ````
CMake Error at CMakeLists.txt:29 (target_link_libraries):
  Target "joy_linux_node" links to:

    diagnostic_updater::diagnostic_updater

  But the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.`
```
I fixed the error by undoing the change in case someone else has the same problem.

**Comment by clalancette** [comment]
> Hi, I'm using Debian 12 bookworm and doing a colcon build, I get the error ````

What ROS distribution are you using?

**Comment by Creador270** [comment]
Rolling installed from source

**Comment by clalancette** [comment]
> Rolling installed from source

I'm unable to reproduce.  Compiling all of Rolling from source on Debian Bookworm, I'm able to compile `joy_linux` just fine.  Do you have `diagnostic_updater` installed?  What does your workspace look like?

**Comment by Creador270** [comment]
the error was coming from the `colcon build --symlink-install` process while I'm installing ros2 rolling probably the error stop the compilation of `diagnostic_updater`

**Pull request merged**
