### PR TITLE
Refactored ROS2 joy_linux

### PR DESCRIPTION
**Pull request by hdino**
I refactored the joy_linux node for ROS2 to improve code readability and added some improvements.

### CODE REVIEW

**Comment by hdino** [comment]
@JWhitleyWork @clalancette : I saw that the joy_linux documentation was not updated for ROS2. If you don't mind, I would add an updated version to this PR.

#168 proposes a feature to figure out a device's name. How do you think about an parameter `enumerate` which, when set to true, simply lists all joysticks and then exits the node?

**Comment by clalancette** [comment]
> #168 proposes a feature to figure out a device's name. How do you think about an parameter `enumerate` which, when set to true, simply lists all joysticks and then exits the node?

For what it is worth, the "joy" node already has a binary which does that, called "joy_enumerate_devices".  I'm not sure it is worthwhile to replicate it in the "joy_linux" node.

**Comment by hdino** [comment]
Sorry, I didn't realise you had already implemented it in the joy node. Then it doesn't make sense to replicate it.

**Comment by clalancette** [comment]
> I refactored the joy_linux node for ROS2 to improve code readability and added some improvements.

Just out of curiousity, is there a reason you can't use the new "joy" node based on SDL2?  While we left "joy_node_linux" for backwards compatibility, I more-or-less consider it deprecated, so I'm not sure it is worth a lot more development on it.

**Comment by hdino** [comment]
Well, I worked on that code for #156, so it was not really more development for me. However, in fact, there is no longer any reason for me to use the Linux node.

The only difference I noticed is that the Linux node recognises the built-in accelerometer of my laptop, while the new joy node does not. However, there is probably no use case for this.

Hence, I agree that the Linux node is not worth a lot more development.

**Comment by JWhitleyWork** [comment]
@hdino So, based on your discussion, can this be closed?

**Comment by hdino** [comment]
@JWhitleyWork Yes, I will close this and delete my fork.

**Pull request closed without merging**
