### PR TITLE
A new driver, which uses (lib)_evdev

### PR DESCRIPTION
**Pull request by FranekStark**
I created a new joy driver, which is based on the libevdev. So it isn't for Joysticks only. You can use every evdev Device `(/dev/input/event#)`. Moreover it also supports force-feedback (well documented).

Have also a look in the README.

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
@FranekStark This is very interesting and a great way to handle the problem of joystick interface. However, it's such a huge change to the infrastructure that I don't think it's a good fit as a PR. I would be happy to put a link to it in the ROS Wiki page as an alternative but, given that the last version of ROS 1 will be released next year and this is such a significant departure from the current, I would rather not merge it at this time.

**Comment by FranekStark** [comment]
@JWhitleyAStuff
Ok, so i‘m going to add instructions for manual installing. 
So if it is the „last“ ROS1 Release, do you think it would be recommend to migrate the Node to Ros2?

**Comment by JWhitleyAStuff** [comment]
I would recommend it, yes. We are in need of a ROS2 port for this repo but another exists in https://github.com/FurqanHabibi/joystick_ros2 as well.

**Comment by FranekStark** [comment]
If I get it right, that node you mentioned is in python and has no ability for force-feedback.

I’m going to port my version, when ever I find enough time. Maybe we can declare it as a “generic Linux HID Node” because of its feature to support any evdev-input-device.

**Pull request closed without merging**
