### PR TITLE
spacenav_node: add a scale parameter to each axis

### PR DESCRIPTION
**Pull request by galou**
Do not apply the scale to the joy topic.

### CODE REVIEW

**Comment by jbohren** [comment]
This looks reasonable. To keep the number of params down, could you use the [`std::vector<float>` suppport](http://docs.ros.org/indigo/api/roscpp/html/namespaceros_1_1param.html#a524016f95d9cb5bd0b0eb6d019e3e119) and just have `linear_scale` and `angular_scale` params, each of which is a length-3 array of doubles?

**Comment by jbohren** [comment]
I believe you can use [this signature to assign a default of `[1,1,1]`](http://docs.ros.org/indigo/api/roscpp/html/namespaceros_1_1param.html#a72d230225ecb3fd770946afd0e1e6af4)

**Comment by galou** [comment]
Thank you for your comment! I did the suggested modification. Scale parameters must be vectors of either 1 or 3 components.

I also forgot to mention that I changed the default dead bands that were not updated with the previous PR (#71, adding the full_scale parameter).

**Comment by jbohren** [comment]
Looks good. I'll test this out and merge soon.

**Comment by galou** [comment]
I just realized that `rosrun spacenav_node spacenav_node _full_scale:=400 _linear_scale:="[2, 3, 4]"` does not work. What also doesn't work is `<rosparam param="/spacenav/angular_scale">[5, 5, 5]</rosparam>` in a launch file. In the second case the parameter is set to `"'[5, 5, 5]'"` (with single quotes) instead of `"[5, 5, 5]"` (without single quotes).
What works is `rosparam set /spacenav/angular_scale "[5, 5, 5]"` in the command line.

Not sure if the problem is in how I pass list parameters to rosparam or how the node handles them. I guess the former.

**Comment by galou** [comment]
Did you find time to test this?

**Comment by jbohren** [comment]
Thanks, @galou, this has been merged through #109!

**Pull request closed without merging**
