### PR TITLE
Add Basic Force Feedback Support

### PR DESCRIPTION
**Pull request by matt-attack**
Addresses issue #89. Tested to work with PS3 controller over USB.

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
@matt-attack I know this has been a while but would you mind fixing the conflicts and testing again?

**Comment by matt-attack** [comment]
Merged, just need to test now.

**Comment by matt-attack** [comment]
Tested and works on my end!

**Comment by JWhitleyAStuff** [comment]
So, @matt-attack - I've finally had some time to review this code in earnest. I'm seeing that your default value for ff_fd_ points to a very specific type of controller on a very specific file location. If you have a different controller plugged in and you attempt to run this node, I'm guessing that you'll get file read errors when trying to open the FF file descriptor. Would you mind adding a parameter to the launch file to enable/disable (with the default being disabled) the FF functionality and only run the functions you've added if that parameter is set to true? This will maintain backwards-compatibility by allowing current users to not have the possibility of getting file descriptor errors when their controller is either not the same model as yours or doesn't support FF in linux.

**Comment by matt-attack** [comment]
Sounds good. Currently it disables the code if the value is set to an empty string so another possibility is to default it to that. However, that means the user will always have to come up with this value themselves so I'll go ahead with your idea instead.

**Comment by JWhitleyAStuff** [comment]
This has been tested by @lbucklandAS and appears to function correctly, even if the launch parameter is not present. Merging.

**Comment by matt-attack** [comment]
Apologies, got caught up in other projects. Is there interest in still adding the parameter?

**Comment by peci1** [comment]
@JWhitleyWork Would you find some time to add relevant docs to http://wiki.ros.org/joy ? I'm mostly concerned with a sample message that could be sent to the node to test if the feedback works. It works for me in fftest, but joy node does nothing... So I opened up the wiki to see how to configure it correctly, and there's not a word...

**Comment by JWhitleyWork** [comment]
@peci1 That would be much appreciated! Sorry for the late reply.

**Comment by peci1** [comment]
@JWhitleyWork I'm confused now. Are you going to edit the wiki or should I try to do it?

**Comment by JWhitleyWork** [comment]
@peci1 Sorry, I would very much appreciate you editing the wiki, if you are able. If not, I'll give it a go but my schedule is tight right now.

**Comment by peci1** [comment]
I've finally added the FF docs :) http://wiki.ros.org/action/info/joy?action=diff&rev2=76&rev1=75

**Pull request merged**
