### PR TITLE
fix high CPU usage when joystick is not connected

### PR DESCRIPTION
**Pull request by tonynajjar**
Addresses https://github.com/ros-drivers/joystick_drivers/issues/246

This might not be a proper fix but it's a start to address the issue and for the maintainer to be able to compare CPU usage

### CODE REVIEW

**Comment by swarajpeppermint** [comment]
Any update on having this pushed into the main repo?

**Comment by tonynajjar** [comment]
> Any update on having this pushed into the main repo?

Never got an answer from the maintainer. @jonbinney?

**Comment by doisyg** [comment]
Confirming your PR fixes the issue for me.
It would be really nice to fix it upstream

**Comment by JWhitleyWork** [comment]
Sorry for the delay. I'm OK with this.

**Pull request merged**
