### PR TITLE
Use INTERFACE_LINK_OPTIONS in sdl2_vendor

### PR DESCRIPTION
**Pull request by cottsay**
The `SDL2_LIBRARIES` value populated by `sdl2-config.cmake` doesn't actually contain the path to the SDL2 library, but rather the linker options necessary to link against SDL2. On Ubuntu, this appears to be `-lSDL2`. On RHEL, this is `-L/usr/lib64 -lSDL2`.

The `OBJECT_LOCATION` property creates a Makefile target that the imported library depends on. On Ubuntu, this utilizes a little-known feature of GNU make where a target that starts with `-l` triggers a search on the VPATH for a library to satisfy the target.

There are two problems here:
1. When `SDL2_LIBRARIES` contains more than just the `-lSDL2` linker option, the aforementioned `VPATH` search doesn't work correctly. You end up with stuff like: `make[2]: *** No rule to make target '-L/usr/lib64  -lSDL2', needed by 'libjoy.so'.  Stop.`
2. The VPATH search may not be able to find `libSDL2.so` if it isn't in a standard location, and the current approach doesn't make any effort to modify the VPATH in the presence of a `-L` option. You end up with stuff like: `make[2]: *** No rule to make target '-lSDL2', needed by 'libjoy.so'.  Stop.`

I'm not sure if the `-l` behavior was known when this change was implemented, or if we just got lucky that this worked out on Ubuntu.

In any case, switching to `INTERFACE_LINK_OPTIONS` is a more appropriate way to use the stuff in the `SDL2_LIBRARIES` value. Unfortunately, a SHARED target requires a backing object, so I had to switch it to an INTERFACE target to make this work. I'm not entirely sure what secondary effects that might have, but it appears to work in all cases that I tested.

Built with `--packages-above-and-dependencies sdl2_vendor`:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13633/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8513/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11347/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13694/)

### CODE REVIEW

**Comment by cottsay** [comment]
Strangely enough, this is working just fine in CI, but the PR job failed. I'll need to investigate that.

**Comment by cottsay** [comment]
Looks like direct access to `INTERFACE_LINK_OPTIONS` is only available in CMake 3.13+, so I switched to `target_link_libraries(INTERFACE)`, which works just as well in this case.

The @ros-tooling CI job is failing for some unrelated reason that the maintainers should have a look at.

The rolling PR job has an unrelated compiler warning coming out of the wiimote code.

**Comment by cottsay** [comment]
The macOS build failure is fixed by #196. None of the failures or warnings I'm seeing here are related to this change.

**Review by clalancette — APPROVED** [review]
Looks good to me.  Now that #196 is merged, can you please run CI again?  macOS should go green (maybe yellow, depending on whether it warns about some other things).

**Comment by cottsay** [comment]
> can you please run CI again

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13675/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8554/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11393/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13742/)

**Comment by clalancette** [comment]
All of the warnings there are from other things (and the Windows one, at least, will be fixed by #202).  Thanks for the fixes, merging.

**Pull request merged**
